name: Production Blue Green Deployment
on:
  workflow_dispatch:
    inputs:
      image:
        required: false
        default: "latest"

jobs:
  deploy_prod_server_1:
    name: Deploying to production servers
    runs-on: [ self-hosted ] 
    env:
      DOCKER_USER: ${{ secrets.PUBLIC_REPO_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}
      IMAGE_VERSION: ${{ github.event.inputs.image || 'latest' }}
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v3
        with:
          ref: ''

      - name: Install jq
        run: sudo apt-get install jq -y

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
          
      - name: Install Ansible
        run: pip install ansible
  
      - name: Deploy application on production server 1
        run: ansible-playbook -i hosts.yml deploy-production.yml -e "run_on_host=prod_server_1 production_server=152.7.177.223 docker_user=$DOCKER_USER docker_password=$DOCKER_PASSWORD image_version=$IMAGE_VERSION"
        working-directory: ./playbooks
        
      - name: Deploy application on production server 2
        run: ansible-playbook -i hosts.yml deploy-production.yml -e "run_on_host=prod_server_2 production_server=152.7.179.1 docker_user=$DOCKER_USER docker_password=$DOCKER_PASSWORD image_version=$IMAGE_VERSION"
        working-directory: ./playbooks

      
