name: Build and Test 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
env:
  REGISTRY: containers.github.ncsu.edu
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:

    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
#         cache: 'npm'
#         cache-dependency-path: ./coffee-project/package-lock.json
    - name: Installing Dependency
      run: npm install
      working-directory: ./coffee-project
#     - name: Linting Application
#       run: npm i lint && 
    - name: Running Tests
      working-directory: ./coffee-project
      run: npm test
      
        
  publish:
    needs: [ build ]
    runs-on: [ self-hosted ]

#     permissions:
#       contents: read
#       packages: write
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./coffee-project
        file: ./Dockerfile
        push: true
        tags: ghcr.io/pipelines/coffee-project:latest
