name: Build and Test 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  
jobs:
  build:

    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
#         cache: 'npm'
#         cache-dependency-path: ./coffee-project/package-lock.json
    - name: Installing Dependency
      run: npm install
      working-directory: ./coffee-project
#     - name: Linting Application
#       run: npm i lint && 
    - name: Running Tests
      working-directory: ./coffee-project
      run: npm test
    
  publish:
    needs: [ build ]
    runs-on: [ self-hosted ]
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
#           cache: 'npm'
#           cache-dependency-path: ./coffee-project/package-lock.json
          
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./coffee-project
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      
