name: Build, Test & Publish

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: [ self-hosted ]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: ./coffee-project/package-lock.json

    - name: Installing Dependency
      run: npm install
      working-directory: ./coffee-project

    - name: Linting Application
      run: npx eslint .
      working-directory: ./coffee-project
      continue-on-error: true

    - name: Running Tests and Coverage
      working-directory: ./coffee-project
      run: npx jest --coverage --forceExit test/app.test.js

    - name: Run ansible-lint
      uses: ansible/ansible-lint@main

  publish:
    needs: build
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/development' || github.event_name == 'workflow_dispatch'
    runs-on: [ self-hosted ]
  
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Public GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PUBLIC_REPO_USERNAME }}  
          password: ${{ secrets.PUBLIC_REPO_PASSWORD }}  
    
      - name: Build Docker image - Master
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: ./coffee-project
          file: ./coffee-project/Dockerfile
          load: true
          tags: ghcr.io/${{ secrets.PUBLIC_REPO_USERNAME }}/coffee-project:latest
    
      - name: Push Docker image to Public GitHub Packages - Master
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ghcr.io/${{ secrets.PUBLIC_REPO_USERNAME }}/coffee-project:latest

      - name: Build Docker image
        if: github.ref != 'refs/heads/master'
        uses: docker/build-push-action@v2
        with:
          context: ./coffee-project
          file: ./coffee-project/Dockerfile
          load: true
          tags: ghcr.io/${{ secrets.PUBLIC_REPO_USERNAME }}/coffee-project:dev
      
      - name: Push Docker image to Public GitHub Packages
        if: github.ref != 'refs/heads/master'
        run: |
          docker push ghcr.io/${{ secrets.PUBLIC_REPO_USERNAME }}/coffee-project:dev