name: Build and Test 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  
jobs:
  build:

    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
#         cache: 'npm'
#         cache-dependency-path: ./coffee-project/package-lock.json
    - name: Installing Dependency
      run: npm install
      working-directory: ./coffee-project
#     - name: Linting Application
#       run: npm i lint && 
    - name: Running Tests
      working-directory: ./coffee-project
      run: npm test
    
  publish:
    needs: [ build ]
    runs-on: [ self-hosted ]
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/coffee-project:latest .
          docker push ghcr.io/${{ github.repository }}/coffee-project:latest
          
      
