name: Build and Test 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  build:

    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
#         cache: 'npm'
#         cache-dependency-path: ./coffee-project/package-lock.json
    - name: Installing Dependency
      run: npm install
      working-directory: ./coffee-project
#     - name: Linting Application
#       run: npm i lint && 
    - name: Running Tests
      working-directory: ./coffee-project
      run: npm test
      
        
  publish:
    needs: [ build ]
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Build and Push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login ghcr.github.ncsu.edu -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

        docker build -t ghcr.github.ncsu.edu/CCDS-CSC-519/DevOps-Pipelines/coffee:latest ./coffee-project

        docker push ghcr.github.ncsu.edu/CCDS-CSC-519/DevOps-Pipelines/coffee:latest

      
