name: Build and Test 

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
  
jobs:
  build:

    runs-on: [ self-hosted ]
    
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js v18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
#         cache: 'npm'
#         cache-dependency-path: ./coffee-project/package-lock.json
    - name: Installing Dependency
      run: npm install
      working-directory: ./coffee-project
#     - name: Linting Application
#       run: npm i lint && 
    - name: Running Tests
      working-directory: ./coffee-project
      run: npm test
    
    
  docker:
    needs: [ build ]
    runs-on: [ self-hosted ]

    steps:
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
        shell: bash
  
  access:
    needs: [ docker ]
    runs-on: self-hosted

    steps:
      - name: Add runner user to docker group
        run: |
          sudo usermod -aG docker $USER
        shell: bash

      - name: Restart Docker
        run: |
          sudo systemctl restart docker
        shell: bash

      - name: Restart GitHub Actions Runner
        run: |
          sudo systemctl restart github-runner
        shell: bash
        
        
  publish:
    needs: [ access ]
    runs-on: [ self-hosted ]
    
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
