#Name of the workflow
name: Deploy Template

#Triggers to run the workflow
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  #Release Job
  release:
    name: Release to ${{ inputs.environment }} # Name of the job
    runs-on: [ self-hosted ] # The type of runner that the job will run on
    environment: # Environment to which the application will be deployed.
      name: ${{ inputs.environment }}
    steps:
      - name: Checkout Repository #Checkout the Repository into the agent
        uses: actions/checkout@v3
        with:
          ref: ''

      - name: Install jq
        run: sudo apt-get install jq

      - name: Set Environment Variables - ${{ inputs.environment }} # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "${{ inputs.environment }}"

      - name: Set up SSH keys
        run: |
          if [ ! -f ~/.ssh/id_rsa ]; then
            # Generate the SSH key if it doesn't exist
            ssh-keygen -t rsa -b 2048 -N "" -f ~/.ssh/id_rsa
            echo "SSH key generated successfully."
          else
            echo "SSH key already exists, skipping key generation."
          fi
          ssh-copy-id -i ~/.ssh/id_rsa.pub agvaicha@${{ env.host_ip }}
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  
          
      - name: Install Ansible
        run: pip install ansible
  
      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: ansible-playbook -i ./playbooks/hosts.yml -l ${{ env.host_group }} ./playbooks/setup-docker.yml