name: Deploy Coffee Project

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted ]
    env:
      DOCKER_USER: ${{ secrets.PUBLIC_REPO_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  
          
    - name: Install Ansible
      run: pip install ansible
        
    - name: Setup Docker runtime using Ansible
      run: ansible-playbook -i ./playbooks/hosts.yml ./playbooks/setup-docker.yml

    - name: Deploy coffee project using Ansible
      run: ansible-playbook -i ./playbooks/hosts.yml -e "run_on_host=dev_server docker_user=$DOCKER_USER docker_password=$DOCKER_PASSWORD" ./playbooks/deploy-application.yml
      
    - name: Open Port 3000 using Ansible
      run: ansible-playbook -i ./playbooks/hosts.yml -e "run_on_host=dev_server port_number=3000" ./playbooks/open-port.yml
