name: Monitor Performance of servers

on:
  workflow_dispatch:

jobs:
  performance_comparison:
    runs-on: [ self-hosted ]
    env:
      VCL_USERNAME: ${{ secrets.VCL_USERNAME }}
      VCL_PASSWORD: ${{ secrets.VCL_PASSWORD }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx paramiko matplotlib

    - name: Run performance comparison
      run: python performance-test.py 152.7.179.29 152.7.177.223 "$VCL_USERNAME" "$VCL_PASSWORD" 2
      working-directory: ./performance-metrics/

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: performance_comparison
        path: ./performance-metrics/performance_comparison.png

