name: Publish Docker image

on:
  workflow_run:
    workflows: ["Build and Test"]
    types: [completed]
    branches:
      - 'master'
      - 'development'
      - 'users/demeht/*'

jobs:
  publish:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - run: echo "This is in demeht branch"
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
  
      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./coffee-project
          file: ./coffee-project/Dockerfile
          load: true  
          tags: ghcr.io/${{ secrets.PUBLIC_REPO_USERNAME }}/coffee-project:latest
  
      - name: Log in to Public GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PUBLIC_REPO_USERNAME }}  
          password: ${{ secrets.PUBLIC_REPO_PASSWORD }}  
  
      - name: Push Docker image to Public GitHub Packages
        run: |
          docker push ghcr.io/${{ secrets.PUBLIC_REPO_USERNAME }}/coffee-project:latest
