name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build, Test & Publish"]
    branches: [master]
    types:
      - completed
  
jobs:
  deploy-dev:
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "dev"
    secrets:
      PUBLIC_REPO_USERNAME: ${{ secrets.PUBLIC_REPO_USERNAME }}
      PUBLIC_REPO_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}

  deploy-qa:
    needs: [deploy-dev]
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "qa"
    secrets:
      PUBLIC_REPO_USERNAME: ${{ secrets.PUBLIC_REPO_USERNAME }}
      PUBLIC_REPO_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}

  qa-tests:
    needs: [deploy-qa]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables - qa # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "qa"

      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./coffee-project/package-lock.json

      - name: Installing Dependency
        run: npm install
        working-directory: ./coffee-project

      - name: Run UI Tests
        run: |
          node test/ui-tests/*.test.js
        working-directory: ./coffee-project

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          # Target URL
          target: "http://${{ env.host_ip }}:3000"
          # The action status will be set to fail if ZAP identifies any alerts during the full scan
          fail_action: false
          issue_title: "OWASP ZAP Scan"
