name: Ansible Deployment

on:
  workflow_dispatch:
  

jobs:
  deploy:
    runs-on: [ self-hosted ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  
        
    - name: Install Ansible
      run: pip install ansible

    - name: Run Ansible playbook
      env:
        ANSIBLE_HOST_KEY_CHECKING: false  
      run: ansible-playbook -i playbooks/hosts.yml playbooks/setup-docker.yml
      working-directory: ${{ github.workspace }}
