name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build, Test & Publish"]
    branches: [master]
    types:
      - completed
  
jobs:
  deploy-dev:
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "dev"
