name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build, Test & Publish"]
    branches: [master]
    types:
      - completed
  
jobs:
  deploy-dev:
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "dev"
    secrets:
      PUBLIC_REPO_USERNAME: ${{ secrets.PUBLIC_REPO_USERNAME }}
      PUBLIC_REPO_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}

  deploy-qa:
    needs: [deploy-dev]
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "qa"
    secrets:
      PUBLIC_REPO_USERNAME: ${{ secrets.PUBLIC_REPO_USERNAME }}
      PUBLIC_REPO_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}

  integration-tests:
    needs: [deploy-qa]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables - qa # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "qa"

      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./coffee-project/package-lock.json

      - name: Installing Dependency
        run: npm install
        working-directory: ./coffee-project

      - name: Run Integration Tests
        working-directory: ./coffee-project
        run: npx jest --forceExit test/integration-tests/*.test.js

  ui-tests:
    needs: [deploy-qa]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables - qa # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "qa"

      - name: Use Node.js v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./coffee-project/package-lock.json

      - name: Installing Dependency
        run: npm install
        working-directory: ./coffee-project

      - name: Run UI Tests
        run: |
          node test/ui-tests/*.test.js
        working-directory: ./coffee-project

  security-tests:
    needs: [deploy-qa]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables - qa # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "qa"

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.8.0
        with:
          # Target URL
          target: "http://${{ env.host_ip }}:3000"
          # The action status will be set to fail if ZAP identifies any alerts during the full scan
          fail_action: false
          allow_issue_writing: false

  deploy-uat:
    needs: [integration-tests, ui-tests, security-tests]
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "uat"
    secrets:
      PUBLIC_REPO_USERNAME: ${{ secrets.PUBLIC_REPO_USERNAME }}
      PUBLIC_REPO_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}

  load-testing:
    needs: [deploy-uat]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables - uat # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "uat"

      #Setup Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      #Install requirements
      - name: Install requirements
        run: pip install -r performance-metrics/requirements.txt

      - name: Run Load Tests
        run: |
          python performance-metrics/load-test.py ${{ env.host_ip }}:3000

  deploy-baking:
    needs: [load-testing]
    uses: CCDS-CSC-519/DevOps-Pipelines/.github/workflows/deploy-template.yml@master #Call the template file
    with:
      environment: "baking"
    secrets:
      PUBLIC_REPO_USERNAME: ${{ secrets.PUBLIC_REPO_USERNAME }}
      PUBLIC_REPO_PASSWORD: ${{ secrets.PUBLIC_REPO_PASSWORD }}

  performance-tests:
    needs: [deploy-baking]
    runs-on: [ self-hosted ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Environment Variables - baking # Set Variables based on environment
        uses: ./.github/actions/set-variable
        with:
          variableFileName: "baking"

      - name: Run Performance Tests
        run: |
          echo "Performance Tests"

  
